name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby-9.2 
        bundler-cache: true 
    - name: Ruby rspec tests
      run: bundle exec rspec
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build gem
      run: gem build logstash-filter-csharp.gemspec
    -
      name: Install in logstash
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile

